name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release-ref.outputs.tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || github.ref }}
      - name: Create release
        id: release-ref
        run: |
          REF="${{ github.event_name == 'workflow_dispatch' && github.sha || github.ref }}"
          TAG_NAME="${REF#refs/tags/}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_NAME="${TAG_NAME:0:12}"
            REF="refs/tags/$TAG_NAME"
          fi
          gh release create "$TAG_NAME" \
            --target "${{ github.event_name == 'workflow_dispatch' && github.sha || github.ref }}" \
            --title "$TAG_NAME" \
            --notes "Release for $TAG_NAME"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    needs: create-release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            binary_name: temple-linux-x86_64
          - target: aarch64-unknown-linux-gnu
            binary_name: temple-linux-aarch64
          - target: x86_64-pc-windows-msvc
            binary_name: temple-windows-x86_64.exe
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || github.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build devShell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default

      - name: Build binary
        shell: 'nix develop -c bash -e {0}'
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Upload binary
        shell: 'nix develop -c bash -e {0}'
        run: |
          if [[ "${{ matrix.target }}" =~ windows ]]; then
            BINARY="target/${{ matrix.target }}/release/temple.exe"
          else
            BINARY="target/${{ matrix.target }}/release/temple"
          fi
          cp "$BINARY" "${{ matrix.binary_name }}"
          gh release upload ${{ needs.create-release.outputs.tag }} "${{ matrix.binary_name }}" --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
